version: '3'

# ============================================================================
# STUDENT CODING ENVIRONMENT - TASKFILE
# ============================================================================
# Build automation for the CoMoSoCo student coding environment.
# Uses uv for Python package management.
#
# Common commands:
#   task install    - Install Python virtual environment
#   task update     - Update all dependencies
#   task pull       - Pull latest from upstream repository
#   task scrub      - Clean environment and caches
#   task status     - Show environment status
# ============================================================================

# ============================================================================
# GLOBAL VARIABLES
# ============================================================================

vars:
  # --- Defaults ---
  VENV_DIR_DEFAULT: '.venv'
  PRIOR_ENV_LOCKS_DEFAULT: '_prior_environments'
  SRC_DIR_DEFAULT: 'comosoco'
  UPSTREAM_REMOTE_DEFAULT: 'upstream'
  UPSTREAM_BRANCH_DEFAULT: 'main'
  UPSTREAM_URL_DEFAULT: 'https://github.com/daeh/comosoco-env.git'

  # --- Resolved (allow override from CLI or environment) ---
  VENV_DIR_RESOLVED: '{{default .VENV_DIR_DEFAULT .VENV_DIR}}'
  PRIOR_ENV_LOCKS_RESOLVED: '{{default .PRIOR_ENV_LOCKS_DEFAULT .PRIOR_ENV_LOCKS}}'
  SRC_DIR_RESOLVED: '{{default .SRC_DIR_DEFAULT .SRC_DIR}}'
  UPSTREAM_REMOTE_RESOLVED: '{{default .UPSTREAM_REMOTE_DEFAULT .UPSTREAM_REMOTE}}'
  UPSTREAM_BRANCH_RESOLVED: '{{default .UPSTREAM_BRANCH_DEFAULT .UPSTREAM_BRANCH}}'
  UPSTREAM_URL_RESOLVED: '{{default .UPSTREAM_URL_DEFAULT .UPSTREAM_URL}}'

  # --- Derived paths ---
  VENV_PATH: '{{joinPath .ROOT_DIR .VENV_DIR_RESOLVED}}'
  VENV_ACTIVATE_PATH: '{{joinPath .VENV_PATH "bin" "activate"}}'
  VENV_PYTHON_PATH: '{{joinPath .VENV_PATH "bin" "python"}}'
  PATH_ENVLOCKS: '{{joinPath .ROOT_DIR .PRIOR_ENV_LOCKS_RESOLVED}}'

tasks:

  # ============================================================================
  # DEFAULT
  # ============================================================================

  default:
    desc: Show available tasks
    silent: true
    cmds:
      - task --list

  # ============================================================================
  # ENVIRONMENT MANAGEMENT
  # ============================================================================

  install:
    desc: Install Python virtual environment (WARNING - overwrites existing env)
    aliases: [env-install]
    prompt: Install Python virtual env? (this will overwrite any existing env)
    platforms: [darwin, linux]
    silent: true
    deps: [_check-installable]
    cmds:
      - printf 'Installing Python virtual environment...\n'
      - task: scrub
      - uv sync
      - task: _exc-store-env-state
      - printf '✅ Environment installed successfully!\n'
      - task: status

  update:
    desc: Update Python dependencies to latest compatible versions
    aliases: [update-deps, env-update]
    silent: true
    deps: [_check-install]
    cmds:
      - printf 'Updating dependencies...\n'
      - uv sync --upgrade
      - task: _exc-store-env-state
      - printf '✅ Dependencies updated successfully!\n'

  update-all:
    desc: Update everything (Homebrew, git upstream, Python dependencies)
    aliases: [full-update]
    silent: true
    cmds:
      - task: update-brew
      - task: pull
      - task: update

  scrub:
    desc: Clean virtual environment and caches (DESTRUCTIVE)
    aliases: [env-scrub, env-clean, clean]
    ignore_error: true
    silent: true
    vars:
      # Static files to remove from project root
      RM_STATIC_FILE_LIST: [
        'uv.lock',
      ]
      # Static directories to remove from project root
      RM_STATIC_DIR_LIST: [
        '{{.VENV_PATH}}',
        '.ruff_cache',
        '.pytest_cache',
        '.task',
      ]
      # File patterns to remove from project root only
      RM_FILE_ROOT_PATTERNS: [
        'requirements*.txt',
      ]
      # Directory patterns to remove recursively throughout project
      RM_DIR_RECURSIVE_PATTERNS: [
        '__pycache__',
        '.ipynb_checkpoints',
        '.jupyter_cache',
      ]
    cmds:
      - printf 'Cleaning project...\n'
      # Remove static files from project root
      - for: { var: RM_STATIC_FILE_LIST }
        cmd: |
          if [ -f "{{.ITEM}}" ]; then
            printf '  Removing %s\n' "{{.ITEM}}"
            rm "{{.ITEM}}"
          fi
      # Remove static directories from project root
      - for: { var: RM_STATIC_DIR_LIST }
        cmd: |
          if [ -d "{{.ITEM}}" ]; then
            printf '  Removing %s/\n' "{{.ITEM}}"
            rm -r "{{.ITEM}}"
          fi
      # Remove files matching patterns in project root
      - for: { var: RM_FILE_ROOT_PATTERNS }
        cmd: >
          find "{{.ROOT_DIR}}"
          -maxdepth 1
          -type f
          -name "{{.ITEM}}"
          -exec printf "  Removing %s\n" {} \;
          -delete
      # Remove directories matching patterns recursively
      - for: { var: RM_DIR_RECURSIVE_PATTERNS }
        cmd: >
          find "{{.ROOT_DIR}}"
          -type d
          -name "{{.ITEM}}"
          -exec printf "  Removing %s\n" {} \;
          -exec rm -r {} + 2>/dev/null || true
      - printf '✅ Clean complete\n'

  # ============================================================================
  # GIT OPERATIONS
  # ============================================================================

  pull:
    desc: Pull latest changes from upstream repository
    aliases: [git-pull, pull-upstream]
    silent: true
    cmds:
      - task: _exc-git-add-remote
      - task: _exc-git-pull
        vars:
          GIT_REMOTE: '{{.UPSTREAM_REMOTE_RESOLVED}}'
          GIT_BRANCH: '{{.UPSTREAM_BRANCH_RESOLVED}}'

  pull-origin:
    desc: Pull latest changes from origin repository
    aliases: [git-pull-origin]
    silent: true
    cmds:
      - task: _exc-git-pull
        vars:
          GIT_REMOTE: 'origin'
          GIT_BRANCH: 'main'

  reset-upstream:
    desc: Hard reset local repo to match upstream (WARNING - DESTRUCTIVE)
    aliases: [git-reset-hard]
    prompt: This overwrites files with versions from upstream. Backup your work first! Continue?
    silent: true
    cmds:
      - task: _exc-check-git
      - task: _exc-git-add-remote
      - printf 'Fetching from %s...\n' "{{.UPSTREAM_REMOTE_RESOLVED}}"
      - git fetch "{{.UPSTREAM_REMOTE_RESOLVED}}"
      - printf '⚠️  Resetting to %s/%s...\n' "{{.UPSTREAM_REMOTE_RESOLVED}}" "{{.UPSTREAM_BRANCH_RESOLVED}}"
      - git reset --hard "{{.UPSTREAM_REMOTE_RESOLVED}}/{{.UPSTREAM_BRANCH_RESOLVED}}"
      - printf '✅ Reset complete\n'

  # ============================================================================
  # UTILITIES
  # ============================================================================

  update-brew:
    desc: Update Homebrew packages (macOS only)
    platforms: [darwin]
    ignore_error: true
    silent: true
    cmds:
      - |
        if command -v brew >/dev/null 2>&1; then
          printf 'Updating Homebrew packages...\n'
          brew update && brew upgrade
          brew cleanup
          brew autoremove
          printf '✅ Homebrew update complete\n'
        else
          printf '⚠️  Homebrew not installed, skipping\n'
        fi

  activate:
    desc: Open a subshell with the virtual environment activated
    aliases: [shell]
    interactive: true
    silent: true
    deps: [_check-install]
    cmds:
      - printf 'Opening shell with virtual environment...\n'
      - printf '  (Type "exit" or press Ctrl+D to return)\n'
      - zsh -i -c 'source "{{.VENV_ACTIVATE_PATH}}" && zsh'

  status:
    desc: Show current environment status
    aliases: [env-status, info]
    silent: true
    cmds:
      - |
        printf '=== Environment Status ===\n'

        if [ -d "{{.VENV_PATH}}" ]; then
          printf '  Virtual environment: ✅ %s\n' "{{.VENV_DIR_RESOLVED}}"
          if [ -f "{{.VENV_PYTHON_PATH}}" ]; then
            PYTHON_VERSION=$("{{.VENV_PYTHON_PATH}}" --version 2>&1)
            printf '    Python: %s\n' "$PYTHON_VERSION"
          fi
        else
          printf '  Virtual environment: ❌ not found\n'
        fi

        if [ -f "uv.lock" ]; then
          printf '  Lock file: ✅ uv.lock\n'
        else
          printf '  Lock file: ❌ missing\n'
        fi

        if [ -f "pyproject.toml" ]; then
          printf '  Project file: ✅ pyproject.toml\n'
        else
          printf '  Project file: ❌ missing\n'
        fi

        printf '\n'
        printf '  Project root: %s\n' "{{.ROOT_DIR}}"
        printf '  Source dir: %s\n' "{{.SRC_DIR_RESOLVED}}"

  # ============================================================================
  # INTERNAL HELPER TASKS
  # ============================================================================

  # --- Check Tasks ---

  _check-installable:
    desc: Check if project can be installed
    internal: true
    preconditions:
      - sh: test -f "pyproject.toml"
        msg: |
          ❌ No pyproject.toml found.
          This file is required for installation.

  _check-install:
    desc: Verify virtual environment is properly installed
    internal: true
    preconditions:
      - sh: test -f "pyproject.toml"
        msg: |
          ❌ No pyproject.toml found.
      - sh: test -f "uv.lock"
        msg: |
          ❌ No uv.lock found. Run 'task install' first.
      - sh: test -d "{{.VENV_PATH}}"
        msg: |
          ❌ Virtual environment not found at {{.VENV_PATH}}.
          Run 'task install' first.
      - sh: test -f "{{.VENV_ACTIVATE_PATH}}"
        msg: |
          ❌ Virtual environment activate script not found.
          Run 'task install' to recreate the environment.

  _exc-check-git:
    desc: Check if Git is installed and initialize repository if needed
    internal: true
    silent: true
    cmds:
      - |
        if ! command -v git >/dev/null 2>&1; then
          printf '❌ Git is not installed\n'
          exit 1
        fi
      - |
        if ! git rev-parse --git-dir > /dev/null 2>&1; then
          printf 'Not a git repository. Initializing...\n'
          git init
          printf '✅ Git repository initialized\n'
        fi

  # --- Execution Helpers ---

  _exc-git-add-remote:
    desc: Add upstream remote if it does not exist
    internal: true
    silent: true
    cmds:
      - |
        if git remote get-url "{{.UPSTREAM_REMOTE_RESOLVED}}" >/dev/null 2>&1; then
          printf '  Remote "%s" exists\n' "{{.UPSTREAM_REMOTE_RESOLVED}}"
        else
          printf '  Adding remote "%s" -> %s\n' "{{.UPSTREAM_REMOTE_RESOLVED}}" "{{.UPSTREAM_URL_RESOLVED}}"
          git remote add "{{.UPSTREAM_REMOTE_RESOLVED}}" "{{.UPSTREAM_URL_RESOLVED}}"
        fi

  _exc-git-pull:
    desc: Fetch and merge from a git remote
    internal: true
    silent: true
    vars:
      # Tracked files that are typically modified in unimportant ways
      RESTORE_FILES: [
        '{{joinPath .SRC_DIR_RESOLVED "installation-test_notebook.ipynb"}}',
      ]
    requires:
      vars: [GIT_REMOTE, GIT_BRANCH]
    cmds:
      - for: { var: RESTORE_FILES }
        cmd: |
          if [ -f "{{.ITEM}}" ]; then
            git restore "{{.ITEM}}" 2>/dev/null || true
          fi
      - printf 'Fetching from %s...\n' "{{.GIT_REMOTE}}"
      - git fetch "{{.GIT_REMOTE}}"
      - git merge "{{.GIT_REMOTE}}/{{.GIT_BRANCH}}"
      - printf '✅ Pull complete\n'

  _exc-store-env-state:
    desc: Save current environment state for rollback
    internal: true
    silent: true
    vars:
      DATE_STR:
        sh: date +%Y-%m-%d
      FNAME_PYPROJECT: 'pyproject-{{.DATE_STR}}.toml'
      FNAME_UVLOCK: 'uv-{{.DATE_STR}}.lock'
      FNAME_PIPFREEZE: 'requirements-{{.DATE_STR}}.txt'
      PATH_PYPROJECT: '{{joinPath .PATH_ENVLOCKS .FNAME_PYPROJECT}}'
      PATH_UVLOCK: '{{joinPath .PATH_ENVLOCKS .FNAME_UVLOCK}}'
      PATH_PIPFREEZE: '{{joinPath .PATH_ENVLOCKS .FNAME_PIPFREEZE}}'
      SNAPSHOT_FILES: [
        '{{.PATH_PYPROJECT}}',
        '{{.PATH_UVLOCK}}',
        '{{.PATH_PIPFREEZE}}',
      ]
    deps: [_check-install]
    cmds:
      - mkdir -p "{{.PATH_ENVLOCKS}}"
      # Remove existing files for today's date (if re-running install)
      - for: { var: SNAPSHOT_FILES }
        cmd: |
          if [ -f "{{.ITEM}}" ]; then
            rm "{{.ITEM}}"
          fi
      # Copy current state
      - cp "pyproject.toml" "{{.PATH_PYPROJECT}}"
      - cp "uv.lock" "{{.PATH_UVLOCK}}"
      # Generate pip freeze (requires activated environment)
      - task: _run
        vars:
          VENV_CMD: "uv pip list --format=freeze > '{{.PATH_PIPFREEZE}}'"
      - printf '  Environment state saved to %s/\n' "{{.PRIOR_ENV_LOCKS_RESOLVED}}"

  _run:
    desc: Run command in activated virtual environment
    internal: true
    requires:
      vars: [VENV_CMD]
    preconditions:
      - sh: test -f "{{.VENV_ACTIVATE_PATH}}"
        msg: |
          ❌ Virtual environment not found.
          Run 'task install' first.
    cmds:
      - zsh -i -c 'source "{{.VENV_ACTIVATE_PATH}}" && {{.VENV_CMD}}'

  # ============================================================================
  # DEBUGGING
  # ============================================================================

  debug:
    desc: Show all paths and variables (for troubleshooting)
    aliases: [env-debug]
    silent: true
    cmds:
      - |
        printf '=== Task Built-in Variables ===\n'
        printf '  ROOT_DIR:           %s\n' '{{.ROOT_DIR}}'
        printf '  TASKFILE_DIR:       %s\n' '{{.TASKFILE_DIR}}'
        printf '  USER_WORKING_DIR:   %s\n' '{{.USER_WORKING_DIR}}'
        printf '\n'
        printf '=== Defaults ===\n'
        printf '  VENV_DIR_DEFAULT:           %s\n' '{{.VENV_DIR_DEFAULT}}'
        printf '  PRIOR_ENV_LOCKS_DEFAULT:    %s\n' '{{.PRIOR_ENV_LOCKS_DEFAULT}}'
        printf '  SRC_DIR_DEFAULT:            %s\n' '{{.SRC_DIR_DEFAULT}}'
        printf '  UPSTREAM_REMOTE_DEFAULT:    %s\n' '{{.UPSTREAM_REMOTE_DEFAULT}}'
        printf '  UPSTREAM_BRANCH_DEFAULT:    %s\n' '{{.UPSTREAM_BRANCH_DEFAULT}}'
        printf '  UPSTREAM_URL_DEFAULT:       %s\n' '{{.UPSTREAM_URL_DEFAULT}}'
        printf '\n'
        printf '=== Resolved ===\n'
        printf '  VENV_DIR_RESOLVED:          %s\n' '{{.VENV_DIR_RESOLVED}}'
        printf '  PRIOR_ENV_LOCKS_RESOLVED:   %s\n' '{{.PRIOR_ENV_LOCKS_RESOLVED}}'
        printf '  SRC_DIR_RESOLVED:           %s\n' '{{.SRC_DIR_RESOLVED}}'
        printf '  UPSTREAM_REMOTE_RESOLVED:   %s\n' '{{.UPSTREAM_REMOTE_RESOLVED}}'
        printf '  UPSTREAM_BRANCH_RESOLVED:   %s\n' '{{.UPSTREAM_BRANCH_RESOLVED}}'
        printf '  UPSTREAM_URL_RESOLVED:      %s\n' '{{.UPSTREAM_URL_RESOLVED}}'
        printf '\n'
        printf '=== Derived Paths ===\n'
        printf '  VENV_PATH:          %s\n' '{{.VENV_PATH}}'
        printf '  VENV_ACTIVATE_PATH: %s\n' '{{.VENV_ACTIVATE_PATH}}'
        printf '  VENV_PYTHON_PATH:   %s\n' '{{.VENV_PYTHON_PATH}}'
        printf '  PATH_ENVLOCKS:      %s\n' '{{.PATH_ENVLOCKS}}'
